export 'package:flutter/material.dart';
export 'package:singleton/singleton.dart';
export 'package:teaching/core/model/response_model.dart';
export '../utils/app_fonts.dart';
export '../utils/app_style.dart';
export 'package:flutter_svg/svg.dart';
export 'package:teaching/core/utils/app_assets.dart';
export '../../config/constants.dart';
export 'package:teaching/service/app.service.dart';
export 'package:teaching/core/model/generic_model.dart';
export 'package:teaching/core/widget/custom_svg.dart';
export 'package:teaching/core/widget/custom_text_widget.dart';
export 'package:teaching/core/utils/extensions.dart';
export 'package:teaching/core/utils/app_lists_constant.dart';
export 'package:teaching/core/utils/size_utils.dart';
export 'package:teaching/core/widget/custom_circle_widget.dart';
export 'package:teaching/core/widget/custom_icon.dart';
export 'package:teaching/features/on_boarding/presentation/widgets/build_first_widget.dart';
export 'package:teaching/core/widget/cached_network_image.dart';
export 'package:teaching/core/widget/custom_background.dart';
export 'package:teaching/core/utils/app_colors.dart';
export 'package:teaching/core/widget/custom_text_form_field.dart';
export 'package:teaching/config/routes/app_routes.dart';
export 'package:teaching/core/widget/custm_card.dart';
export 'package:teaching/features/auth/presentation/widgets/sign_up/build_form_field.dart';
export 'package:teaching/core/widget/custom_elevated_button.dart';
export 'package:teaching/core/helper/app_helper.dart';
export 'package:teaching/features/auth/presentation/widgets/sign_up/build_next_button.dart';
export 'package:teaching/features/auth/presentation/widgets/build_app_bar.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export '../../../../core/managers/error_manager/error_cubit.dart';
export 'package:teaching/core/widget/error_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/email_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/phone_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/identity_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/name_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/password_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/confrm_password_widget.dart';
export 'package:teaching/core/widget/custom_drop_down.dart';
export 'package:teaching/features/auth/presentation/pages/sign_up_screen.dart';
export 'package:teaching/core/helper/general_dialog.dart';
export 'package:teaching/features/auth/presentation/pages/sign_up_py_phone_screen.dart';
export 'package:teaching/core/widget/custom_image_widget.dart';
export 'package:teaching/features/auth/presentation/widgets/choose_role/build_choose_role_app_bar.dart';
export 'package:teaching/core/list_states.dart';
export 'package:teaching/features/bottom_nav_bar/presentaion/manager/onboading_operation_cubit.dart';
export 'package:teaching/features/bottom_nav_bar/presentaion/widget/build_nav_bar.dart';
export '../../../../core/widget/custom_list_view.dart';
export 'package:dio/dio.dart';
export 'package:flutter/foundation.dart';

export '../../../../core/resonse_messages.dart';
export '../../../../core/response_code.dart';
export '../../../../core/network/abstract/failure.dart';
export '../../../../core/network/network_enums.dart';
export 'package:flutter_rating_bar/flutter_rating_bar.dart';
export 'package:teaching/core/widget/build_rating_bar.dart';
export 'package:shared_preferences/shared_preferences.dart';
export '../../../../core/local_storage/app_prefs.dart';
export 'package:teaching/features/language/presentation/managers/language_cubit/language_cubit.dart';
export 'package:teaching/service_locator.dart';
export 'package:teaching/core/utils/app_strings.dart';
export 'package:teaching/features/auth/presentation/widgets/sign_up/build_dotte_border.dart';
export 'package:teaching/core/enums.dart';
export 'package:teaching/core/widget/custom_divider.dart';
export  'package:teaching/features/auth/service/register_service.dart';
export 'package:teaching/features/auth/presentation/widgets/sign_up/build_upload_promo.dart';

export 'package:teaching/core/network/constants/endpoinst.dart';
export 'package:teaching/features/auth/data/models/verification_model.dart';
export '../../../../core/network/impl/dio_impl/dio-consumer.dart';
export 'package:teaching/features/auth/data/models/user_response_model.dart';
export 'package:teaching/features/auth/data/models/post_params_education_model.dart';
export 'package:teaching/core/model/couses_model.dart';
export 'package:teaching/core/model/groups_model.dart';
export 'package:teaching/features/home/data/models/courses_groups_response_model.dart';
export '../../../../../core/model/generic_response_model.dart';
export'package:teaching/core/widget/custom_empty_widget.dart';
export'package:teaching/core/widget/common_item_widgets/custom_item.dart';
export'package:teaching/features/home/presentation/manager/courses_groups_cubit.dart';
export'../../../../core/widget/custom_error_widget.dart';
export 'package:teaching/core/widget/common_widgets/custom_sared_full_screen.dart';


